### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by AndrewTru** [hahoyer/factorio-mod-ingteb#1]
using 248K and this mod plus needed mods.
1. start a game
2. load into game
3. hit ingted button
4. \/

The mod Ingame Technology browser (0.5.5) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event ingteb::on_gui_click (ID 1)
__ingteb__/ingteb/ModuleCategory.lua:18: attempt to index field '?' (a nil value)
stack traceback:
	__ingteb__/ingteb/ModuleCategory.lua:18: in function <__ingteb__/ingteb/ModuleCategory.lua:16>
	__ingteb__/core/ValueCache.lua:39: in function 'Ensure'
	__ingteb__/core/ValueCache.lua:20: in function <__ingteb__/core/ValueCache.lua:19>
	(...tail calls...)
	__ingteb__/core/classclass.lua:58: in function '__index'
	__ingteb__/core/classclass.lua:15: in function 'GetField'
	__ingteb__/core/classclass.lua:58: in function '__index'
	__ingteb__/ingteb/ModuleCategory.lua:47: in function <__ingteb__/ingteb/ModuleCategory.lua:46>
	__ingteb__/core/ValueCache.lua:39: in function 'Ensure'
	__ingteb__/core/ValueCache.lua:20: in function <__ingteb__/core/ValueCache.lua:19>
	(...tail calls...)
	__ingteb__/core/classclass.lua:58: in function '__index'
	...
	__ingteb__/core/Table.lua:99: in function 'Select'
	__ingteb__/ingteb/Selector.lua:200: in function 'GetSubGroupPanel'
	__ingteb__/ingteb/Selector.lua:220: in function 'getItem'
	__ingteb__/core/Table.lua:305: in function 'ToArray'
	__ingteb__/ingteb/Selector.lua:218: in function 'GetAllItemsGui'
	__ingteb__/ingteb/Selector.lua:119: in function 'GetGuiInnerVariant'
	__ingteb__/ingteb/Selector.lua:101: in function 'GetGui'
	__ingteb__/ingteb/Selector.lua:36: in function 'Open'
	__ingteb__/ingteb/EventManager.lua:113: in function 'ToggleFloating'
	__ingteb__/ingteb/Gui.lua:39: in function 'OnGuiEvent'
	__ingteb__/ingteb/EventManager.lua:378: in function <__ingteb__/ingteb/EventManager.lua:370>

**Comment by hahoyer** [comment]
Can you provide a save-file. This would probably speedup things.

**Comment by hahoyer** [comment]
Can reproduce it.

**Comment by hahoyer** [comment]
Fixed in 0.5.6
